Feat hide clear button
opf/primer_view_components pull request #174
Opened 2024-09-04 12:07 UTC by dombesz

### What are you trying to accomplish?
Introduce a functionality to show and hide the clear button of the SubHeader component filter input. The clear button is shown when the filter input has some value typed in, and it is hidden when the input is empty.

### Integration
No, when the `show_clear_button: true` argument is passed to the `component.with_filter_input`, the added functionality will work automatically.

#### List the issues that this change affects.
https://community.openproject.org/wp/55234

#### Risk Assessment
- [X] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?
Added a new method `toggleFilterInputClearButton` to the `SubHeaderElement` which will decide whether the clear button should be displayed or not. This method is then triggered on the filter input `focus` and `input` events, ensuring that the clear button is shown only when there is content inside the input field.

### Anything you want to highlight for special attention from reviewers?

Would be nice to have the `PrimerTextFieldElement#clearContents` method updated to emit an input event. That way the `toggleFilterInputClearButton` shouldn't be bound to both the `focus` and the `input` event, just the latter. This has been an issue for another functionality before, so I might need to make that change PR against the main primer repo, not this one.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [X] Added/updated previews (Lookbook)
- [X] Tested in Chrome
- [X] Tested in Firefox
- [X] Tested in Safari
- [ ] Tested in Edge

2024-09-09 07:52 UTC, HDinger requested changes
I have some minor remarks. I think we should set `show_clear_button` to true as a default for text inputs in the SubHeaders. Wdyt?

2024-09-09 07:52 UTC, HDinger commented on app/components/primer/open_project/sub_header.rb
> +          system_arguments[:data][:action] = <<~ACTION
I don't know this syntax. Does it allow to pass custom data-actions or will they be overwritten? 

There is a helper, that we could use to merge data attributes: `merge_data`

2024-09-09 07:52 UTC, HDinger commented on app/components/primer/open_project/sub_header_element.ts
> +  #setupFilterInputClearButton() {
Please do not use special characters in the name of a method.
```suggestion
  setupFilterInputClearButton() {
```

2024-09-09 07:52 UTC, HDinger commented on app/components/primer/open_project/sub_header_element.ts
> +  #waitForCondition(condition: () => boolean, body: () => void) {
Same as above
```suggestion
  waitForCondition(condition: () => boolean, body: () => void) {
```

2024-09-09 07:52 UTC, HDinger commented on app/components/primer/open_project/sub_header_element.ts
> +      this.clearButtonWrapper.classList.add('FormControl-input-wrap--trailingAction')
This is bad style, mainly because of three reasons: 

1. If the class name changes, this will break
2. It is hard to foresee what other things are connected to this class. Currently it only sets the padding. But in the future, other styles might be added which would then got lost 
3. Due to the toggleing of the class, the input jumps in its width

My suggestion would be to leave that class untouched and accept that the placeholder will not span the whole width. We could increase the default width of the input instead to avoid that anybody notices it at all. I suggest to do that separatley however. It makes sense to do that whe providing the fix for `input_width` in the SubHeader.

2024-09-09 08:55 UTC, dombesz commented on app/components/primer/open_project/sub_header_element.ts
> +  #setupFilterInputClearButton() {
This pattern was borrowed from the primer repository. Removed.

2024-09-09 10:51 UTC, HDinger commented on app/components/primer/open_project/sub_header_element.ts
> +        this.clearButtonWrapper = this.clearFilterButton.closest('.FormControl-input-wrap') as HTMLElement
What do you need this `clearButtonWrapper` for?

2024-09-10 07:19 UTC, HDinger approved these changes
Good to merge once the CI is green

2024-09-10 07:30 UTC, merged