[59468] Danger Confirmation Dialog implementation
opf/primer_view_components pull request #214
Opened 2024-12-11 23:41 UTC by myabc

Based on `FeedbackDialog`. Wraps `Primer::Alpha::Dialog`, providing additional standardised behaviour for scenarios where a user performs a "dangerous" action.

Includes initial Lookbook previews and component tests.

Implements `DangerConfirmationDialogFormHelperElement` Catalyst controller providing checkbox confirmation behaviour.

https://community.openproject.org/projects/openproject/work_packages/58680

_Authors: Please fill out this form carefully and completely._

_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._

### What are you trying to accomplish?

### Screenshots

### Integration

#### List the issues that this change affects.

Closes # (type the GitHub issue number after #)

#### Risk Assessment
  

- [ ] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

### Anything you want to highlight for special attention from reviewers?

### Accessibility

- **Fixes axe scan violation** - This change fixes an existing [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation.
- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

2024-12-12 13:26 UTC, HDinger requested changes
Hi @myabc 

nice job, it looks really good 👍 I only have some minor remarks.

2024-12-12 13:26 UTC, HDinger commented on previews/primer/open_project/danger_confirmation_dialog_preview.rb
> +      # @param loading_state [Boolean] toggle
I think we should not show the loading_state as option as it does not make much sense for the danger dialog

2024-12-12 13:26 UTC, HDinger commented on previews/primer/open_project/danger_confirmation_dialog_preview/playground.html.erb
> +      <%= render(Primer::Alpha::Banner.new) { "Some additional content below" } %>
This example looks somehow weird:

<img width="512" alt="Bildschirmfoto 2024-12-12 um 14 14 44" src="https://github.com/user-attachments/assets/07d0dc2c-c404-4030-b2e1-7d84452bc24c" />

2024-12-16 19:32 UTC, myabc commented on app/components/primer/open_project/danger_confirmation_dialog.rb
> +        @system_arguments[:id] = @dialog_id
I've moved the assignment. Let me know if that works for you?

2024-12-16 20:40 UTC, myabc commented on previews/primer/open_project/danger_confirmation_dialog_preview/playground.html.erb
> +      <%= render(Primer::Alpha::Banner.new) { "Some additional content below" } %>
I've updated the Preview example - I think we can leave it up to the caller not to override styling of additional details with `:inline`.

<img width="508" alt="image" src="https://github.com/user-attachments/assets/630ecfb8-6a23-4f67-839d-8ead08b2c0d5" />

2024-12-16 21:34 UTC, myabc commented
@HDinger I've addressed most of the issues you raised.

In addition to the couple of questions inline, a couple general questions:

* Should we use `checkbox`/`Checkbox` or `check_box`/`CheckBox`? The HTML spec uses `checkbox`, and is what I would normally prefer. It's one less keystroke for our end users. However the latter would make us consistent with the other Primer components.
* `DangerConfirmationDialog` is a pretty long, cumbersome name IMO. "confirmation" is probably redundant, given that our slots also our named `confirmation_message` and `confirmation_dialog`. Could we consider going with just (an opinionated) `DangerDialog`?

2024-12-16 21:41 UTC, myabc commented on app/components/primer/open_project/danger_confirmation_dialog.html.erb
> +          <% if additional_details? %>
I will rename the `FeedbackDialog` `additional_content` slot to `additional_details` in a separate PR.

2024-12-16 21:52 UTC, myabc commented on app/components/primer/open_project/danger_confirmation_dialog/confirmation_checkbox.rb
> +            render(Primer::Alpha::CheckBox.new(**@checkbox_arguments.merge(label: trimmed_content)))
@HDinger As I've implemented it, we build the checkbox label based on (`trimmed_`)`content` - this allows for a similar API to the other slots, i.e.:

```ruby
      dialog.with_show_button { "Click me" }
      dialog.with_confirmation_checkbox { "I confirm this deletion" }
```

An alternative would be to add a `label_text` string parameter - either on `DangerConfirmationDialog` itself - or on the slot. I am not sure "what feels" more idiomatic?

```ruby
  DangerConfirmationDialog.new(label_text: "I confirm this deletion")
  dialog.with_confirmation_checkbox(label_text: "I confirm this deletion")
```

2024-12-16 22:02 UTC, myabc commented on app/components/primer/open_project/danger_confirmation_dialog/confirmation_checkbox.rb
> +            render(Primer::Alpha::CheckBox.new(**@checkbox_arguments.merge(label: trimmed_content)))
Also, do we want to define a `I18n.t` default for the label? Or is it fine to always leave it to the caller?

2024-12-17 07:32 UTC, HDinger requested changes
I left some remarks and will check what is happening with the snapshots.

2024-12-17 07:32 UTC, HDinger commented on .changeset/brave-eggs-obey.md
> +"@openproject/primer-view-components": patch
please make that a `minor`  release

2024-12-17 07:32 UTC, HDinger commented on test/components/component_test.rb
> +    [Primer::OpenProject::DangerConfirmationDialog::ConfirmationCheckbox, {}],
I think we can ignore this from the tests. At the bottom of the file, there is a list of exlcuded classes, where you can simply add this.

2024-12-17 07:32 UTC, HDinger commented on app/components/primer/open_project/danger_confirmation_dialog/confirmation_checkbox.rb
> +            render(Primer::Alpha::CheckBox.new(**@checkbox_arguments.merge(label: trimmed_content)))
Currently you can write something like `dialog.with_confirmation_checkbox` which will render a checkbox without any label. So we either have to provide a default or enforce that the user provides a string. Since the default is rather special, we probably have to enforce the the user to pass an argument for now. 

With regards to the syntax, I like the `dialog.with_confirmation_checkbox { "I confirm this deletion" }` notation, but if it is easier to enfoce a text with a named parameter, I am also fine with that.

2024-12-17 07:32 UTC, HDinger commented on app/components/primer/open_project/danger_confirmation_dialog.html.erb
> +        <%= render(Primer::Beta::Button.new(scheme: :danger, data: { "submit-dialog-id": dialog_id })) { I18n.t("button_delete_permanently") } %>
The button currently does not submit the form when being pressed. `"submit-dialog-id"` only closes the Dialog but does not trigger any form update.

2024-12-19 10:47 UTC, myabc commented on app/components/primer/open_project/danger_confirmation_dialog.html.erb
> +        <%= render(Primer::Beta::Button.new(scheme: :danger, data: { "submit-dialog-id": dialog_id })) { I18n.t("button_delete_permanently") } %>
Fixed in [aa84913](https://github.com/opf/primer_view_components/pull/214/commits/aa8491308535550bedfdde88eec2f102f3f7d074)

2024-12-20 01:40 UTC, myabc commented on test/components/component_test.rb
> +    [Primer::OpenProject::DangerConfirmationDialog::ConfirmationCheckbox, {}],
I went ahead and ignored the internal `Primer::OpenProject::DangerConfirmationDialog::FormWrapper` component, as you suggested. I've am not sure why that is preferable though?

2024-12-20 07:40 UTC, HDinger commented on test/components/component_test.rb
> +    [Primer::OpenProject::DangerConfirmationDialog::ConfirmationCheckbox, {}],
We usually ignore those components that are more helper components of their parents and don't make too much sense standalone. Those will be tested in the scope of their parents and not individually. I think it is fine the way you did it 👍

2024-12-20 07:42 UTC, HDinger approved these changes
Nice job 🌟  I really like the way it can be used 👍

2024-12-20 07:42 UTC, merged