feat[#50499]: Add back button and breadcrumbs to page header
opf/primer_view_components pull request #45
Opened 2023-10-26 09:18 UTC by dominic-braeunlein

Work package: https://community.openproject.org/wp/50499
Related PR in OP: https://github.com/opf/openproject/pull/13962

### What are you trying to accomplish?

This PR adds breadcrumbs and back button support to the PageHeader.

A breadcrumbs item can be:
- An object with href and text e.g.` {href: "/admin", text: "Admin" }`.
- An Anchor-tag string wich can be the return value from `breadcrumb_paths` method in `BreadcrumbHelper` e.g. `"\u003ca href=\"/root/sub\"\u003eSub\u003c/a\u003e"
`.
- Or a text which is useful for the last element / current url e.g. `"Page 2"`

This feature also adds an optional `show_breadcrumb` parameter to deactivate rendering of the breadcrumbs. Which helps harmonisation with the existing `BreadcrumbHelper` `#show_local_breadcrumb` control method to maintain backwards compatibility.

e.g.
```
breadcrumb_items = [
  "test1",
  "test2" ,
  "test3"
]
render(Primer::OpenProject::PageHeader.new) do |header|
  header.with_title() { "Hello" }
  header.with_back_button(href: "#")
  header.with_breadcrumbs(breadcrumb_items, show_breadcrumb: false)
end
```

### Screenshots
<img width="924" alt="Screenshot 2023-10-26 at 14 54 16" src="https://github.com/opf/primer_view_components/assets/1113942/d2cbbf17-3c69-4dbb-8136-90ba74949702">

#### List the issues that this change affects.
https://community.openproject.org/wp/50499

#### Risk Assessment
  

- [x] **Low risk** the change is small, highly observable, and easily rolled back.
- [ ] **Medium risk** changes that are isolated, reduced in scope or could impact few users. The change will not impact library availability.
- [ ] **High risk** changes are those that could impact customers and SLOs, low or no test coverage, low observability, or slow to rollback.

### What approach did you choose and why?

### Anything you want to highlight for special attention from reviewers?

### Accessibility

- **Fixes axe scan violation** - This change fixes an existing [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation.
- **No new axe scan violation** - This change does not introduce any new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violations.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Added/updated previews (Lookbook)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

2023-10-30 11:22 UTC, akabiru reviewed
Looks good to me! 🎉 I left a few remarks but would leave to @HDinger for final approval 🥇

2023-10-30 11:22 UTC, akabiru commented on app/components/primer/open_project/page_header.rb
> +        system_arguments[:aria] = { label: I18n.t("button_back") }
Nice accessibility catch 👍🏾

2023-10-30 11:22 UTC, akabiru commented on app/components/primer/open_project/page_header.rb
> +        system_arguments[:aria] = { label: I18n.t("button_back") }
It might be worth defining these attributes as defaults, to allow overriding in different cases. IMO most are fine as "hardcoded" except the The `size` might not always be `:medium` and the aria label could change.

Looking at the title slot example: https://github.com/opf/primer_view_components/blob/main/app/components/primer/open_project/page_header.rb#L22-L31

2023-10-30 11:22 UTC, akabiru commented on app/components/primer/open_project/page_header.rb
> +      end
Tip: `rubocop -a app/components/primer/open_project/page_header.rb` might sort this out

https://github.com/rubocop/rubocop

2023-10-30 11:22 UTC, akabiru commented on previews/primer/open_project/page_header_preview.rb
> +          {href: "/root", text: "Root"},
`rubocop -a previews/primer/open_project/page_header_preview.rb` as well to get spacing 👍🏾

2023-10-30 12:24 UTC, HDinger requested changes
Hi @dominic-braeunlein 

Looks good 👍 I have some remarks in the code, some of them we might want to discuss. 

 - [ ] Further I noticed that the arrow is not correctly aligned with the header text:
<img width="155" alt="Bildschirmfoto 2023-10-30 um 12 40 53" src="https://github.com/opf/primer_view_components/assets/7457313/9398b455-2a1f-4668-b1ff-b2e4ac1f40aa">

- [ ] At least some of the CI failures are due to missing specs. So please add tests for the newly added features. You can add them [here](https://github.com/opf/primer_view_components/blob/main/test/components/primer/open_project/page_header_test.rb). Let me know, if you need help with the other failing tests.

2023-10-30 12:25 UTC, HDinger commented on app/components/primer/open_project/page_header.rb
> +        render(Primer::Beta::Breadcrumbs.new(classes: ["PageHeader-breadcrumbs"] )) do |breadcrumbs|
I think one of the failing tests might even be failing due to the missing `system_arguments`

2023-10-31 09:00 UTC, dominic-braeunlein commented on app/components/primer/open_project/page_header.rb
> +      renders_one :breadcrumbs, lambda { |items, show_breadcrumb: true|
Good question, I was a bit unsure of the convention here.

I personally think it is an array of items that get rendered at once, similar to the **actions** slot and it should be called breadcrumbs for rendering one bar of breadcrumb-items
https://github.com/opf/primer_view_components/blob/main/app/components/primer/open_project/page_header.rb#L45

On the other hand, in the **BreadcrumbHelper** we have a method called **show_breadcrumb** which is why I ended up with **show_breadcrumb** as argument name instead of **show_breadcrumbs**

I am fine with either. Either way it's probably a good idea to have the slot name **breadcrumb** and **show_breadcrumbs** harmonised.

2023-10-31 10:21 UTC, dominic-braeunlein commented on app/components/primer/open_project/page_header.rb
> +      end
Thank you! I got RuboCop running now

2023-10-31 10:22 UTC, dominic-braeunlein commented on app/components/primer/open_project/page_header.rb
> +        system_arguments[:aria] = { label: I18n.t("button_back") }
Makes sense. Thank you, I removed it.

2023-10-31 10:22 UTC, dominic-braeunlein commented on app/components/primer/open_project/page_header.rb
> +        system_arguments[:classes] = class_names(system_arguments[:classes], "PageHeader-back_button")
Adjusted, thank you

2023-11-02 08:32 UTC, HDinger requested changes
Hi @dominic-braeunlein 

Nice job, I only have minor remarks. 👍 Further @bsatarnejad noticed that on mobile the text is not wrapping correctly around the arrow:

<img width="220" alt="Bildschirmfoto 2023-11-02 um 09 28 18" src="https://github.com/opf/primer_view_components/assets/7457313/648c7bc5-7e29-4122-a239-a8af9a52c9c3">

I'd expect the arrow to stay on the right side, and the text to wrap after it. What do you think?

2023-11-07 13:53 UTC, dominic-braeunlein commented
> Hi @dominic-braeunlein
> 
> Nice job, I only have minor remarks. 👍 Further @bsatarnejad noticed that on mobile the text is not wrapping correctly around the arrow:
> 
> <img alt="Bildschirmfoto 2023-11-02 um 09 28 18" width="220" src="https://user-images.githubusercontent.com/7457313/279914162-648c7bc5-7e29-4122-a239-a8af9a52c9c3.png">
> I'd expect the arrow to stay on the right side, and the text to wrap after it. What do you think?



Hi @HDinger,
thank you! I went for following solution to wrap the title:


<img width="394" alt="Screenshot 2023-11-07 at 19 26 21" src="https://github.com/opf/primer_view_components/assets/1113942/517e3f01-cab5-48c3-87c7-3c4b54f9bc55">
<img width="398" alt="Screenshot 2023-11-07 at 19 26 12" src="https://github.com/opf/primer_view_components/assets/1113942/a922ac4d-8110-42f9-94fc-c3644acfcfbf">



I had to change the [HTML](https://github.com/opf/primer_view_components/pull/45/files#diff-5ba9e16aea915812351c4129fa6a0fed8c6fa8807d844122865b081ca2252ffdR3) structure in the PageHeader to achieve this result, which resulted also in [CSS changes](https://github.com/opf/primer_view_components/pull/45/files#diff-fedf6c4dbe005ddf15c1720adcaa59454625a4e9f107fe1d494fdf6a4cb0e036R8). Please have a look and let me know if it is ok to have a div in the template.

While I was changing the CSS I saw that the [order](https://github.com/opf/primer_view_components/pull/45/files#diff-fedf6c4dbe005ddf15c1720adcaa59454625a4e9f107fe1d494fdf6a4cb0e036L20) attributes could be removed now. Please double check this too, maybe I am missing something.

2023-11-08 10:11 UTC, HDinger reviewed
Hi @dominic-braeunlein 

> I had to change the [HTML](https://github.com/opf/primer_view_components/pull/45/files#diff-5ba9e16aea915812351c4129fa6a0fed8c6fa8807d844122865b081ca2252ffdR3) structure in the PageHeader to achieve this result, which resulted also in [CSS changes](https://github.com/opf/primer_view_components/pull/45/files#diff-fedf6c4dbe005ddf15c1720adcaa59454625a4e9f107fe1d494fdf6a4cb0e036R8). Please have a look and let me know if it is ok to have a div in the template.
 
That is totally okay 👍 
 
> While I was changing the CSS I saw that the [order](https://github.com/opf/primer_view_components/pull/45/files#diff-fedf6c4dbe005ddf15c1720adcaa59454625a4e9f107fe1d494fdf6a4cb0e036L20) attributes could be removed now. Please double check this too, maybe I am missing something.
 
Yes, seems to work fine 👍 

The component looks good to me. I have some minor remarks with regards to the preview.
Further, I had a look on the figma specification and saw that there are some special mobile styles: The back button is hidden, as well as the breadcumb and a different navigation element is shown. In Primer, this is named the [context bar](https://primer.style/components/page-header#context-bar) of the page header. We can add that in a separate PR to get this one done, but need to keep in mind, that we hide the backButton and breadcrumbs.

2023-11-08 10:11 UTC, HDinger commented on previews/primer/open_project/page_header_preview/actions.html.erb
> +    Hello this is a long title for testing
Please do not use the previews for testing. You can use the "playground" preview for exactly these cases.

2023-11-08 10:11 UTC, HDinger commented on previews/primer/open_project/page_header_preview.rb
> +      def back_button_and_breadcrumbs
I think we should keep the previews isolated, or at least have an isolated "breadcrumbs" preview.

2023-11-08 10:11 UTC, HDinger commented on previews/primer/open_project/page_header_preview.rb
> +      # @label Back button
Please add the backButton and the breadcrumb as options to the "playground". At least with a Boolean toggle to enable/disbale them.

2023-11-08 11:56 UTC, dominic-braeunlein commented on previews/primer/open_project/page_header_preview/actions.html.erb
> +    Hello this is a long title for testing
Makes sense, now I get it.

2023-11-08 12:57 UTC, dominic-braeunlein commented
> ... and saw that there are some special mobile styles: The back button is hidden, as well as the breadcumb and a different navigation element is shown. In Primer, this is named the [context bar](https://primer.style/components/page-header#context-bar) of the page header. We can add that in a separate PR to get this one done, but need to keep in mind, that we hide the backButton and breadcrumbs.

Hi @HDinger
Perfect, I will create a new PR for that.


After I added the new parameters to the playground I saw a small misalignment:
The back button (even when set to large) doesn't align perfectly when the title is set to large .
I would look further into this if you think it is necessary. I just didn't find an obvious fix for it. What do you think?

Also, thank you for all your input! 

<img width="1014" alt="Screenshot 2023-11-08 at 18 30 33" src="https://github.com/opf/primer_view_components/assets/1113942/079d8e18-1ee0-45f1-8abe-2ab38a9cc54e">

2023-11-09 07:10 UTC, HDinger commented
> After I added the new parameters to the playground I saw a small misalignment:
> The back button (even when set to large) doesn't align perfectly when the title is set to large .
> I would look further into this if you think it is necessary. I just didn't find an obvious fix for it. What do you think?

Yeah, I would like to have that solved. I can support you with this, if you like.

2023-11-09 08:44 UTC, HDinger approved these changes
Good to merge 👍  Thanks for all the effort @dominic-braeunlein !

2023-11-09 09:21 UTC, merged